// <auto-generated />
using System;
using ChummyFoodBack.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CraftyCornerBack.Migrations
{
    [DbContext(typeof(CommerceContext))]
    [Migration("20231220231951_AddedAvailableCount")]
    partial class AddedAvailableCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.CategoryDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.IdentityDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleDaoId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RoleDaoId");

                    b.ToTable("Identity");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.PaymentDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateOfCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DateOfResolove")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdentityId")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceCode")
                        .HasColumnType("longtext");

                    b.Property<string>("InvoiceUrl")
                        .HasColumnType("longtext");

                    b.Property<double>("PaymentAmount")
                        .HasColumnType("double");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("StoredPaymentType")
                        .HasColumnType("int");

                    b.Property<int?>("VoucherActivationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.HasIndex("VoucherActivationId")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.ProductCostItemsDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("OwnedBy")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UserUnderstandableItem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OwnedBy");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCostItems");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.ProductDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductDownText")
                        .HasColumnType("longtext");

                    b.Property<string>("UnitOfPrice")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.RequestedProductToBuyDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ItemsCountRequested")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentDAOId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentDAOId");

                    b.HasIndex("ProductId");

                    b.ToTable("RequestedProductToBuy");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.RestoreCodeDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdentityId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Issued")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RestoreCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("Valid")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.ToTable("RestoreCode");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.RoleDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.SiteDisplayDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("HeaderText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SiteDisplay");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.VoucherActivationDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ActivationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoucherId");

                    b.ToTable("VoucherActivation");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.VoucherDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Discount")
                        .HasColumnType("double");

                    b.Property<DateTimeOffset>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("IssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Voucher")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Voucher");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.IdentityDAO", b =>
                {
                    b.HasOne("ChummyFoodBack.Persistance.DAO.RoleDao", "RoleDao")
                        .WithMany()
                        .HasForeignKey("RoleDaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleDao");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.PaymentDAO", b =>
                {
                    b.HasOne("ChummyFoodBack.Persistance.DAO.IdentityDAO", "Identity")
                        .WithMany("Payments")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChummyFoodBack.Persistance.DAO.VoucherActivationDAO", "VoucherActivation")
                        .WithOne("Payment")
                        .HasForeignKey("ChummyFoodBack.Persistance.DAO.PaymentDAO", "VoucherActivationId");

                    b.Navigation("Identity");

                    b.Navigation("VoucherActivation");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.ProductCostItemsDAO", b =>
                {
                    b.HasOne("ChummyFoodBack.Persistance.DAO.PaymentDAO", "Payment")
                        .WithMany("ProductCostItems")
                        .HasForeignKey("OwnedBy");

                    b.HasOne("ChummyFoodBack.Persistance.DAO.ProductDAO", "Product")
                        .WithMany("ProductCostItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.ProductDAO", b =>
                {
                    b.HasOne("ChummyFoodBack.Persistance.DAO.CategoryDAO", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.RequestedProductToBuyDAO", b =>
                {
                    b.HasOne("ChummyFoodBack.Persistance.DAO.PaymentDAO", null)
                        .WithMany("RequestedProducts")
                        .HasForeignKey("PaymentDAOId");

                    b.HasOne("ChummyFoodBack.Persistance.DAO.ProductDAO", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.RestoreCodeDAO", b =>
                {
                    b.HasOne("ChummyFoodBack.Persistance.DAO.IdentityDAO", "Identity")
                        .WithMany("RestoreCodes")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.VoucherActivationDAO", b =>
                {
                    b.HasOne("ChummyFoodBack.Persistance.DAO.VoucherDAO", "Voucher")
                        .WithMany("VoucherActivations")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.CategoryDAO", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.IdentityDAO", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("RestoreCodes");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.PaymentDAO", b =>
                {
                    b.Navigation("ProductCostItems");

                    b.Navigation("RequestedProducts");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.ProductDAO", b =>
                {
                    b.Navigation("ProductCostItems");
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.VoucherActivationDAO", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("ChummyFoodBack.Persistance.DAO.VoucherDAO", b =>
                {
                    b.Navigation("VoucherActivations");
                });
#pragma warning restore 612, 618
        }
    }
}
